name: Deploy Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug SSH
        run: |
          getent ahosts ${{ secrets.SERVER_HOST }}

          ssh-keygen -lf ~/.ssh/id_ed25519

          ssh -vvv \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "whoami"